# Dockerfile.jenkins-controller (Simplified for Root Execution)

# Start from the official Jenkins image
FROM jenkins/jenkins:lts-jdk17

# Switch to the root user to install software
USER root

# Install the Docker CLI using the official convenience script
RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://get.docker.com -o get-docker.sh && \
    sh get-docker.sh

# We will run the final container as root, so no need to switch back to the 'jenkins' user.