# The name of your workflow. This is what shows up in the GitHub Actions tab.
name: CI-Pipeline

# This section defines *when* the workflow should run.
on:
  # Run on every push to the 'main' branch.
  push:
    branches: [ "main" ]
  # Also run on every pull request that targets the 'main' branch.
  pull_request:
    branches: [ "main" ]

# This section defines the actual work to be done.
jobs:
  # We are defining a single "job" called "lint-and-format".
  lint-and-format:
    # This specifies what kind of machine to run the job on.
    # 'ubuntu-latest' is a standard, free virtual machine provided by GitHub.
    runs-on: ubuntu-latest

    # This section lists the individual steps the job will perform in order.
    steps:
      # Step 1: Check out the repository's code.
      # This downloads a copy of your code onto the virtual machine.
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment.
      # This action installs a specific version of Python for us.
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install our dependencies, including our linter.
      # A linter is a tool that checks code for style errors.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Step 4: Run the linter.
      # This command tells flake8 to check all Python files for errors.
      # It ignores certain non-critical errors (like lines being too long).
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics